/*
 * ControlPanel.java
 * Created by John Melton G0ORX
 * Created on 01-Feb-2010, 12:47:52
 * 
 */

/*
 * This code has been and reviewed modified.
 * John Tucker, N8MDP
 */

/*
 * Revsion History
 * 02/01/13: Changes:
 *              1. Added direct buttons to change  bands (160, 80, 60,40, 30,
 *                  20, 17, 15, 12, 10, 6 Meters, GEN, WWV1, WWV2, WWV3)
 *              2. Eliminated the original Band button to select the band and
 *                  its associated code
 *              3. Enlarged the VFO display
 *              4. Added a second VFO so that you can direct enter a frequency.
 *                  Added the "A>B" button to transfer the frequency.
 * 
 * 1/20/13: Changes:
 *              1. public void updatedVFO ()
 *                  A. Added code to properly set the mode (e.g. LSB, USB..)
 *                  B. Added code to set the Master/Slave mode indicator
 *                  C. Added code to update the Digital Meter.
 * 		2. Added two new functions for the UP/DN VFO
 *                  A. private void freqUpActionPerformed
 *                      => Increases the VFO setting by 1000Hz	
 *                  B. private void freqDownActionPerformed
 *			=> Decreases the VFO setting by 1000Hz	
 * 
 */

package jmonitor;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButtonMenuItem;

public class ControlPanel extends javax.swing.JPanel {

    /** Creates new form ControlPanel */
    public ControlPanel() {
        initComponents();

        vfo.setCaretColor(Color.WHITE);
    
        createLSBFilterMenu();
        createModeMenu();
        createAGCMenu();
        createDSPMenu();
        createGainMenu();
    }

    public void setClient(Client client) {
        this.client=client;
    }

    
    // I am adding this code to just update the Frequency VFO and the String Mode
    public void updateVFO () {
        frequency=client.getFrequency();
        String fString=mhzFormat.format(frequency/1000000)+"."+khzFormat.format(frequency%1000000);
        vfo.setText(fString); 
        modeString=client.getStringMode();
        mode.setText(modeString);
        msID.setText(client.getmsMode());
        digitalMeter.update(client.getMeter());
    }
 
    public void update() {
// Not sure this function is even called!!! Will review
        if(client.getFrequency()!=frequency) {
            frequency=client.getFrequency();
            String fString=mhzFormat.format(frequency/1000000)+"."+khzFormat.format(frequency%1000000);
            vfo.setText(fString);
        }

        if(!modeString.equals(client.getStringMode())) {
            modeString=client.getStringMode();
            mode.setText(client.getStringMode());
        }
        
        digitalMeter.update(client.getMeter());
        

    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        button2 = new java.awt.Button();
        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        modeButton = new javax.swing.JButton();
        vfo = new javax.swing.JTextField();
        mode = new javax.swing.JTextField();
        digitalMeter = new jmonitor.DigitalMeter();
        filterButton = new javax.swing.JButton();
        agcButton = new javax.swing.JButton();
        dspButton = new javax.swing.JButton();
        afgainButton = new javax.swing.JButton();
        msID = new javax.swing.JTextField();
        freqUp = new java.awt.Button();
        freqDown = new java.awt.Button();
        band60Mbutton = new javax.swing.JButton();
        band80Mbutton = new javax.swing.JButton();
        band160Mbutton = new javax.swing.JButton();
        band20Mbutton = new javax.swing.JButton();
        band40Mbutton = new javax.swing.JButton();
        band30Mbutton = new javax.swing.JButton();
        band17Mbutton = new javax.swing.JButton();
        band15Mbutton = new javax.swing.JButton();
        band12Mbutton = new javax.swing.JButton();
        band10Mbutton = new javax.swing.JButton();
        band6Mbutton = new javax.swing.JButton();
        WWV1button = new javax.swing.JButton();
        WWV2button = new javax.swing.JButton();
        bandGENbutton = new javax.swing.JButton();
        WWV3button = new javax.swing.JButton();
        inputVFO = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        vfoAtoB = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        button2.setLabel("button2");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(960, 27));
        setMinimumSize(new java.awt.Dimension(960, 27));
        setPreferredSize(new java.awt.Dimension(960, 27));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modeButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        modeButton.setText("Mode");
        modeButton.setAlignmentY(0.0F);
        modeButton.setMaximumSize(new java.awt.Dimension(90, 27));
        modeButton.setMinimumSize(new java.awt.Dimension(90, 27));
        modeButton.setPreferredSize(new java.awt.Dimension(90, 27));
        modeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeButtonActionPerformed(evt);
            }
        });
        add(modeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 80, 30));

        vfo.setEditable(false);
        vfo.setBackground(new java.awt.Color(0, 0, 0));
        vfo.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        vfo.setForeground(new java.awt.Color(0, 255, 0));
        vfo.setText("7.048.000");
        vfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vfo.setMaximumSize(new java.awt.Dimension(178, 26));
        vfo.setMinimumSize(new java.awt.Dimension(178, 26));
        vfo.setPreferredSize(new java.awt.Dimension(178, 26));
        vfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vfoMouseClicked(evt);
            }
        });
        vfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vfoActionPerformed(evt);
            }
        });
        add(vfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 250, 60));

        mode.setEditable(false);
        mode.setBackground(new java.awt.Color(0, 0, 0));
        mode.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        mode.setForeground(new java.awt.Color(0, 255, 0));
        mode.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mode.setText("LSB");
        mode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeActionPerformed(evt);
            }
        });
        add(mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 80, 50));

        javax.swing.GroupLayout digitalMeterLayout = new javax.swing.GroupLayout(digitalMeter);
        digitalMeter.setLayout(digitalMeterLayout);
        digitalMeterLayout.setHorizontalGroup(
            digitalMeterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        digitalMeterLayout.setVerticalGroup(
            digitalMeterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        add(digitalMeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, 20));

        filterButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        filterButton.setText("Filter");
        filterButton.setMaximumSize(new java.awt.Dimension(90, 27));
        filterButton.setMinimumSize(new java.awt.Dimension(90, 27));
        filterButton.setPreferredSize(new java.awt.Dimension(90, 27));
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });
        add(filterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 90, 30));

        agcButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        agcButton.setText("AGC");
        agcButton.setMaximumSize(new java.awt.Dimension(90, 27));
        agcButton.setMinimumSize(new java.awt.Dimension(90, 27));
        agcButton.setPreferredSize(new java.awt.Dimension(90, 27));
        agcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agcButtonActionPerformed(evt);
            }
        });
        add(agcButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 80, 30));

        dspButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        dspButton.setText("DSP");
        dspButton.setMaximumSize(new java.awt.Dimension(90, 27));
        dspButton.setMinimumSize(new java.awt.Dimension(90, 27));
        dspButton.setPreferredSize(new java.awt.Dimension(90, 27));
        dspButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dspButtonActionPerformed(evt);
            }
        });
        add(dspButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 80, 30));

        afgainButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        afgainButton.setText("AF Gain");
        afgainButton.setMaximumSize(new java.awt.Dimension(90, 27));
        afgainButton.setMinimumSize(new java.awt.Dimension(90, 27));
        afgainButton.setPreferredSize(new java.awt.Dimension(90, 27));
        afgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afgainButtonActionPerformed(evt);
            }
        });
        add(afgainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 90, 30));

        msID.setEditable(false);
        msID.setBackground(new java.awt.Color(0, 0, 0));
        msID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        msID.setForeground(new java.awt.Color(0, 255, 0));
        msID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        msID.setText("Master-Mode");
        msID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msIDActionPerformed(evt);
            }
        });
        add(msID, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 110, 30));

        freqUp.setBackground(new java.awt.Color(255, 255, 255));
        freqUp.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        freqUp.setLabel("UP");
        freqUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freqUpActionPerformed(evt);
            }
        });
        add(freqUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 40, 30));

        freqDown.setBackground(new java.awt.Color(255, 255, 255));
        freqDown.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        freqDown.setLabel("DN");
        freqDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freqDownActionPerformed(evt);
            }
        });
        add(freqDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 40, 30));

        band60Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band60Mbutton.setText("60");
        band60Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band60MbuttonActionPerformed(evt);
            }
        });
        add(band60Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 30));

        band80Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band80Mbutton.setText("80");
        band80Mbutton.setToolTipText("");
        band80Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band80MbuttonActionPerformed(evt);
            }
        });
        add(band80Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 30));

        band160Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band160Mbutton.setText("160");
        band160Mbutton.setToolTipText("");
        band160Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band160MbuttonActionPerformed(evt);
            }
        });
        add(band160Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        band20Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band20Mbutton.setText("20");
        band20Mbutton.setToolTipText("");
        band20Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band20MbuttonActionPerformed(evt);
            }
        });
        add(band20Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 30));

        band40Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band40Mbutton.setText("40");
        band40Mbutton.setToolTipText("");
        band40Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band40MbuttonActionPerformed(evt);
            }
        });
        add(band40Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 60, 30));

        band30Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band30Mbutton.setText("30");
        band30Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band30MbuttonActionPerformed(evt);
            }
        });
        add(band30Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 60, 30));

        band17Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band17Mbutton.setText("17");
        band17Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band17MbuttonActionPerformed(evt);
            }
        });
        add(band17Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 60, 30));

        band15Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band15Mbutton.setText("15");
        band15Mbutton.setToolTipText("");
        band15Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band15MbuttonActionPerformed(evt);
            }
        });
        add(band15Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 60, 30));

        band12Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band12Mbutton.setText("12");
        band12Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band12MbuttonActionPerformed(evt);
            }
        });
        add(band12Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 60, 30));

        band10Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band10Mbutton.setText("10");
        band10Mbutton.setToolTipText("");
        band10Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band10MbuttonActionPerformed(evt);
            }
        });
        add(band10Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 60, 30));

        band6Mbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        band6Mbutton.setText("6");
        band6Mbutton.setToolTipText("");
        band6Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band6MbuttonActionPerformed(evt);
            }
        });
        add(band6Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 60, 30));

        WWV1button.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        WWV1button.setText("WWV 5");
        WWV1button.setToolTipText("");
        WWV1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WWV1buttonActionPerformed(evt);
            }
        });
        add(WWV1button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 90, 30));

        WWV2button.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        WWV2button.setText("WWV 10");
        WWV2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WWV2buttonActionPerformed(evt);
            }
        });
        add(WWV2button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 90, 30));

        bandGENbutton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bandGENbutton.setText("GEN");
        bandGENbutton.setToolTipText("");
        bandGENbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandGENbuttonActionPerformed(evt);
            }
        });
        add(bandGENbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 60, 30));

        WWV3button.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        WWV3button.setText("WWV 15");
        WWV3button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WWV3buttonActionPerformed(evt);
            }
        });
        add(WWV3button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 90, 30));

        inputVFO.setBackground(new java.awt.Color(0, 0, 0));
        inputVFO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        inputVFO.setForeground(new java.awt.Color(0, 255, 0));
        inputVFO.setText("7.173000");
        inputVFO.setToolTipText("");
        inputVFO.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputVFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVFOActionPerformed(evt);
            }
        });
        add(inputVFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 140, 30));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("VFO A");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 50, 30));

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 255, 0));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("VFO B");
        jTextField2.setToolTipText("");
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 50, 30));

        vfoAtoB.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        vfoAtoB.setText("A > B");
        vfoAtoB.setToolTipText("");
        vfoAtoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vfoAtoBActionPerformed(evt);
            }
        });
        add(vfoAtoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 90, 30));

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 255, 0));
        jTextField3.setText("MHz");
        jTextField3.setToolTipText("");
        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void createModeMenu() {

        ButtonGroup group=new ButtonGroup();

        JRadioButtonMenuItem item;

        modeMenu = new JPopupMenu("Mode");
        
        item=new JRadioButtonMenuItem("LSB");
        lsb=item;
        item.setSelected(true);
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(0);
                client.setFilter(-2850, -150);
                createLSBFilterMenu();
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("USB");
        usb=item;
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(1);
                client.setFilter(150, 2850);
                createUSBFilterMenu();
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("DSB");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(2);
                client.setFilter(-2600, 2600);
                createAMFilterMenu();
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("CWL");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(3);
                client.setFilter(-800, -400);
                createCWFilterMenu();
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("CWU");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(4);
                client.setFilter(400, 800);
                createCWFilterMenu();
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("SPEC");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(8);
                client.setFilter(-6000, -6000);
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("DIGL");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(9);
                client.setFilter(-3450, -150);
                createDIGLFilterMenu();
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("DIGU");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(7);
                client.setFilter(150, 3450);
                createDIGUFilterMenu();
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("DRM");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(11);
                client.setFilter(-6000, 6000);
                filterMenu=null;
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("AM");
        am=item;
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(6);
                client.setFilter(-4000,4000);
                createAMFilterMenu();
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("SAM");
        sam=item;
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(10);
                client.setFilter(-4000,4000);
                createAMFilterMenu();
            }
        });
        group.add(item);
        modeMenu.add(item);

        item = new JRadioButtonMenuItem("FMN");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setMode(5);
                client.setFilter(-2600, 2600);
                createAMFilterMenu();
            }
        });
        group.add(item);
        modeMenu.add(item);

    }

    
    
    private void modeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeButtonActionPerformed
        modeMenu.show(modeButton, 0, 0);
    }//GEN-LAST:event_modeButtonActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        if(filterMenu!=null) {
            filterMenu.show(filterButton, 0, 0);
        }
    }//GEN-LAST:event_filterButtonActionPerformed

    private void agcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agcButtonActionPerformed
        if(agcMenu!=null) {
            agcMenu.show(agcButton, 0, 0);
        }
    }//GEN-LAST:event_agcButtonActionPerformed

    private void dspButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dspButtonActionPerformed
        if(dspMenu!=null) {
            dspMenu.show(dspButton, 0, 0);
        }
    }//GEN-LAST:event_dspButtonActionPerformed

    private void vfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vfoActionPerformed
        // This function no longer works due to the timer updates... JLT
        // user has entered a frequency
        String s=vfo.getText().replace(".","");
        try {
            long f=Long.parseLong(s);
            client.setFrequency(f);
        } catch (Exception e) {
            // force repaint
            frequency=0L;
        }
    }//GEN-LAST:event_vfoActionPerformed

    private void afgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afgainButtonActionPerformed
        if(gainMenu!=null) {
            gainMenu.show(afgainButton,0,0);
        }
    }//GEN-LAST:event_afgainButtonActionPerformed

    private void vfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vfoMouseClicked
        // look for right mouse event
        if(evt.getButton()==evt.BUTTON3) {

        }
    }//GEN-LAST:event_vfoMouseClicked

    private void msIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msIDActionPerformed

    private void freqUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freqUpActionPerformed
        client.setFrequency(client.getFrequency()+1000);
    }//GEN-LAST:event_freqUpActionPerformed

    private void freqDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freqDownActionPerformed
        client.setFrequency(client.getFrequency()-1000);
    }//GEN-LAST:event_freqDownActionPerformed

    private void band160MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band160MbuttonActionPerformed
        client.setFrequency(1850000);
        client.setFilter(-3440, -150);
        client.setMode(Client.modeLSB);
        lsb.setSelected(true);
        createLSBFilterMenu();
    }//GEN-LAST:event_band160MbuttonActionPerformed

    private void band80MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band80MbuttonActionPerformed
        client.setFrequency(3750000);
        client.setFilter(-3440, -150);
        client.setMode(Client.modeLSB);
        lsb.setSelected(true);
        createLSBFilterMenu();
    }//GEN-LAST:event_band80MbuttonActionPerformed

    private void band60MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band60MbuttonActionPerformed
        client.setFrequency(5371500);
        client.setFilter(-3440, -150);
        client.setMode(Client.modeLSB);
        lsb.setSelected(true);
        createLSBFilterMenu();
    }//GEN-LAST:event_band60MbuttonActionPerformed

    private void band40MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band40MbuttonActionPerformed
        client.setFrequency(7150000);
        client.setFilter(-3440, -150);
        client.setMode(Client.modeLSB);
        lsb.setSelected(true);
        createLSBFilterMenu();
    }//GEN-LAST:event_band40MbuttonActionPerformed

    private void band30MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band30MbuttonActionPerformed
        client.setFrequency(10135600);
        client.setFilter(150, 3440);
        client.setMode(Client.modeUSB);
        usb.setSelected(true);
        createUSBFilterMenu();
    }//GEN-LAST:event_band30MbuttonActionPerformed

    private void band20MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band20MbuttonActionPerformed
        client.setFrequency(14175000);
        client.setFilter(150, 3440);
        client.setMode(Client.modeUSB);
        usb.setSelected(true);
        createUSBFilterMenu();
    }//GEN-LAST:event_band20MbuttonActionPerformed

    private void band17MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band17MbuttonActionPerformed
        client.setFrequency(18118900);
        client.setFilter(150, 3440);
        client.setMode(Client.modeUSB);
        usb.setSelected(true);
        createUSBFilterMenu();
    }//GEN-LAST:event_band17MbuttonActionPerformed

    private void band15MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band15MbuttonActionPerformed
        client.setFrequency(21225000);
        client.setFilter(150, 3440);
        client.setMode(Client.modeUSB);
        usb.setSelected(true);
        createUSBFilterMenu();
    }//GEN-LAST:event_band15MbuttonActionPerformed

    private void band12MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band12MbuttonActionPerformed
        client.setFrequency(24940000);
        client.setFilter(150, 3440);
        client.setMode(Client.modeUSB);
        usb.setSelected(true);
        createUSBFilterMenu();
    }//GEN-LAST:event_band12MbuttonActionPerformed

    private void band10MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band10MbuttonActionPerformed
        client.setFrequency(28500000);
        client.setFilter(150, 3440);
        client.setMode(Client.modeUSB);
        usb.setSelected(true);
        createUSBFilterMenu();
    }//GEN-LAST:event_band10MbuttonActionPerformed

    private void band6MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band6MbuttonActionPerformed
        client.setFrequency(52000000);
        client.setFilter(150, 3440);
        client.setMode(Client.modeUSB);
        usb.setSelected(true);
        createUSBFilterMenu();
    }//GEN-LAST:event_band6MbuttonActionPerformed

    private void bandGENbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandGENbuttonActionPerformed
        client.setFrequency(909000);
        client.setFilter(-4000,4000);
        client.setMode(Client.modeAM);
        am.setSelected(true);
        createAMFilterMenu();
    }//GEN-LAST:event_bandGENbuttonActionPerformed

    private void WWV1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WWV1buttonActionPerformed
        client.setFrequency(5000000);
        client.setFilter(-4000,4000);
        client.setMode(Client.modeSAM);
        sam.setSelected(true);
        createAMFilterMenu();
    }//GEN-LAST:event_WWV1buttonActionPerformed

    private void WWV2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WWV2buttonActionPerformed
        client.setFrequency(10000000);
        client.setFilter(-4000,4000);
        client.setMode(Client.modeSAM);
        sam.setSelected(true);
        createAMFilterMenu();
    }//GEN-LAST:event_WWV2buttonActionPerformed

    private void WWV3buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WWV3buttonActionPerformed
        client.setFrequency(15000000);
        client.setFilter(-4000,4000);
        client.setMode(Client.modeSAM);
        sam.setSelected(true);
        createAMFilterMenu();
    }//GEN-LAST:event_WWV3buttonActionPerformed

    private void modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void vfoAtoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vfoAtoBActionPerformed
        // This code takes any input and puts into the proper format as 
        // long as the frequency entered is in MHz        
        DecimalFormat df = new DecimalFormat("##0.000000");
//        String s=inputVFO.getText().replace(".","");
        String s=inputVFO.getText();
        double freq = Double.valueOf(s);
        s = df.format(freq);
        s = s.replace(".","");
        try {
            
            long f=Long.parseLong(s);
            client.setFrequency(f);
        } catch (Exception e) {
            // force repaint
            frequency=0L;
        }
    }//GEN-LAST:event_vfoAtoBActionPerformed

    private void inputVFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVFOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVFOActionPerformed

    private void createLSBFilterMenu() {

        ButtonGroup group=new ButtonGroup();
        JRadioButtonMenuItem item;

        filterMenu = new JPopupMenu("Filter");


        item=new JRadioButtonMenuItem("5.0k");
        item.addActionListener (new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-5150,-150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("4.4k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-4550, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("3.8k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-3950, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("3.3k");
        item.setSelected(true);
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-3440, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.9k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-3050, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.7k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-2850, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.4k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-2550, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.1k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-2250, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("1.8k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-1950, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("1.0k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-1150, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);
    }

    private void createUSBFilterMenu() {

        ButtonGroup group=new ButtonGroup();
        JRadioButtonMenuItem item;

        filterMenu = new JPopupMenu("Filter");

        item=new JRadioButtonMenuItem("5.0k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150,5150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("4.4k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150,4550);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("3.8k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150,3950);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("3.3k");
        item.setSelected(true);
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150,3440);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.9k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150,3050);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.7k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150,2850);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.4k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150,2550);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.1k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150,2250);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("1.8k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150,1950);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("1.0k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150,1150);
            }
        });
        group.add(item);
        filterMenu.add(item);
    }

    private void createCWFilterMenu() {
        ButtonGroup group=new ButtonGroup();
        JRadioButtonMenuItem item=new JRadioButtonMenuItem();

        filterMenu = new JPopupMenu("Filter");

        item=new JRadioButtonMenuItem("1.0k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(client.getMode()==Client.modeCWL) {
                    client.setFilter(-client.getCWPitch()-500,-client.getCWPitch()+500);
                } else {
                    client.setFilter(client.getCWPitch()-500,client.getCWPitch()+500);
                }
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("800");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(client.getMode()==Client.modeCWL) {
                    client.setFilter(-client.getCWPitch()-400,-client.getCWPitch()+400);
                } else {
                    client.setFilter(client.getCWPitch()-400,client.getCWPitch()+400);
                }
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("750");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(client.getMode()==Client.modeCWL) {
                    client.setFilter(-client.getCWPitch()-375,-client.getCWPitch()+375);
                } else {
                    client.setFilter(client.getCWPitch()-375,client.getCWPitch()+375);
                }
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("600");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(client.getMode()==Client.modeCWL) {
                    client.setFilter(-client.getCWPitch()-300,-client.getCWPitch()+300);
                } else {
                    client.setFilter(client.getCWPitch()-300,client.getCWPitch()+300);
                }
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("500");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(client.getMode()==Client.modeCWL) {
                    client.setFilter(-client.getCWPitch()-250,-client.getCWPitch()+250);
                } else {
                    client.setFilter(client.getCWPitch()-250,client.getCWPitch()+250);
                }
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("400");
        item.setSelected(true);
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(client.getMode()==Client.modeCWL) {
                    client.setFilter(-client.getCWPitch()-200,-client.getCWPitch()+200);
                } else {
                    client.setFilter(client.getCWPitch()-200,client.getCWPitch()+200);
                }
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("250");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(client.getMode()==Client.modeCWL) {
                    client.setFilter(-client.getCWPitch()-125,-client.getCWPitch()+125);
                } else {
                    client.setFilter(client.getCWPitch()-125,client.getCWPitch()+125);
                }
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("100");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(client.getMode()==Client.modeCWL) {
                    client.setFilter(-client.getCWPitch()-50,-client.getCWPitch()+50);
                } else {
                    client.setFilter(client.getCWPitch()-50,client.getCWPitch()+50);
                }
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("50");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(client.getMode()==Client.modeCWL) {
                    client.setFilter(-client.getCWPitch()-25,-client.getCWPitch()+25);
                } else {
                    client.setFilter(client.getCWPitch()-25,client.getCWPitch()+25);
                }
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("25");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(client.getMode()==Client.modeCWL) {
                    client.setFilter(-client.getCWPitch()-13,-client.getCWPitch()+13);
                } else {
                    client.setFilter(client.getCWPitch()-13,client.getCWPitch()+13);
                }
            }
        });
        group.add(item);
        filterMenu.add(item);
    }


    private void createDIGLFilterMenu() {
        ButtonGroup group=new ButtonGroup();
        JRadioButtonMenuItem item=new JRadioButtonMenuItem();

        filterMenu = new JPopupMenu("Filter");

        item=new JRadioButtonMenuItem("5.0k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-5150, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("4.4k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-4550, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("3.8k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-3950, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("3.3k");
        item.setSelected(true);
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-3440, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.9k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-3050, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.7k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-2850, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.4k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-2550, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.1");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-2250, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("1.8k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-1950, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("1.0k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-1150, -150);
            }
        });
        group.add(item);
        filterMenu.add(item);
    }

    private void createDIGUFilterMenu() {
        ButtonGroup group=new ButtonGroup();
        JRadioButtonMenuItem item;

        filterMenu = new JPopupMenu("Filter");
        
        item=new JRadioButtonMenuItem("5.0k");
        filterMenu.add("5.0k").addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150, 5150);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("4.4k");
        filterMenu.add("4.4k").addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150, 4550);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("3.8k");
        filterMenu.add("3.8k").addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150, 3950);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("3.3k");
        item.setSelected(true);
        filterMenu.add("3.3k").addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150, 3440);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.9k");
        filterMenu.add("2.9k").addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150, 3050);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.7k");
        filterMenu.add("2.7k").addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150, 2850);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.4k");
        filterMenu.add("2.4k").addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150, 2550);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.1k");
        filterMenu.add("2.1k").addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150, 2250);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("1.8k");
        filterMenu.add("1.8k").addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150, 1950);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("1.0k");
        filterMenu.add("1.0k").addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(150, 1150);
            }
        });
        group.add(item);
        filterMenu.add(item);
    }

    private void createAMFilterMenu() {
        ButtonGroup group=new ButtonGroup();
        JRadioButtonMenuItem item;

        filterMenu = new JPopupMenu("Filter");
        
        item=new JRadioButtonMenuItem("16.0k");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-8000,8000);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("12.0k");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-6000,6000);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("10.0k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-5000,5000);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("8.0k");
        item.setSelected(true);
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-4000,4000);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("6.6k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-3300,3300);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("5.2k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-2600,2600);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("4.0k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-2000,2000);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("3.1k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-1550,1550);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.9k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-1450,1450);
            }
        });
        group.add(item);
        filterMenu.add(item);

        item=new JRadioButtonMenuItem("2.4k");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setFilter(-1200,1200);
            }
        });
        group.add(item);
        filterMenu.add(item);
    }

    private void createAGCMenu() {
        ButtonGroup group=new ButtonGroup();
        JRadioButtonMenuItem item;

        agcMenu = new JPopupMenu("AGC");
        item=new JRadioButtonMenuItem("Long");
        item.setSelected(true);
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setAGC(1);
            }
        });
        group.add(item);
        agcMenu.add(item);

        item=new JRadioButtonMenuItem("Slow");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setAGC(2);
            }
        });
        group.add(item);
        agcMenu.add(item);

        item=new JRadioButtonMenuItem("Medium");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setAGC(3);
            }
        });
        group.add(item);
        agcMenu.add(item);

        item=new JRadioButtonMenuItem("Fast");
        item.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client.setAGC(4);
            }
        });
        group.add(item);
        agcMenu.add(item);
    }

    private void createDSPMenu() {
        dspMenu = new JPopupMenu("DSP");
        JCheckBoxMenuItem item=new JCheckBoxMenuItem("NR");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setNR(item.getState());
           }
        });
        dspMenu.add(item);
        item=new JCheckBoxMenuItem("ANF");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setANF(item.getState());
           }
        });
        dspMenu.add(item);
        item=new JCheckBoxMenuItem("NB");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setNB(item.getState());
           }
        });
        dspMenu.add(item);
    }

    private void createGainMenu() {
        ButtonGroup group=new ButtonGroup();
        gainMenu = new JPopupMenu("AF Gain");
        JCheckBoxMenuItem item=new JCheckBoxMenuItem("0");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(0);
           }
        });
        gainMenu.add(item);
        group.add(item);
        item=new JCheckBoxMenuItem("10");

        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(10);
           }
        });
        gainMenu.add(item);
        group.add(item);
        item=new JCheckBoxMenuItem("20");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(20);
           }
        });
        gainMenu.add(item);
        group.add(item);
        
        item=new JCheckBoxMenuItem("30");
        item.setSelected(true);
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(30);
           }
        });
        gainMenu.add(item);
        group.add(item);
        item=new JCheckBoxMenuItem("40");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(40);
           }
        });
        gainMenu.add(item);
        group.add(item);
        item=new JCheckBoxMenuItem("50");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(50);
           }
        });
        gainMenu.add(item);
        group.add(item);
        item=new JCheckBoxMenuItem("60");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(60);
           }
        });
        gainMenu.add(item);
        group.add(item);
        item=new JCheckBoxMenuItem("70");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(70);
           }
        });
        gainMenu.add(item);
        group.add(item);
        item=new JCheckBoxMenuItem("80");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(80);
           }
        });
        gainMenu.add(item);
        group.add(item);
        item=new JCheckBoxMenuItem("90");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(90);
           }
        });
        gainMenu.add(item);
        group.add(item);
        item=new JCheckBoxMenuItem("100");
        item.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               JCheckBoxMenuItem item=(JCheckBoxMenuItem)evt.getSource();
               client.setGain(100);
           }
        });
        gainMenu.add(item);
        group.add(item);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton WWV1button;
    private javax.swing.JButton WWV2button;
    private javax.swing.JButton WWV3button;
    private javax.swing.JButton afgainButton;
    private javax.swing.JButton agcButton;
    private javax.swing.JButton band10Mbutton;
    private javax.swing.JButton band12Mbutton;
    private javax.swing.JButton band15Mbutton;
    private javax.swing.JButton band160Mbutton;
    private javax.swing.JButton band17Mbutton;
    private javax.swing.JButton band20Mbutton;
    private javax.swing.JButton band30Mbutton;
    private javax.swing.JButton band40Mbutton;
    private javax.swing.JButton band60Mbutton;
    private javax.swing.JButton band6Mbutton;
    private javax.swing.JButton band80Mbutton;
    private javax.swing.JButton bandGENbutton;
    private java.awt.Button button2;
    private jmonitor.DigitalMeter digitalMeter;
    private javax.swing.JButton dspButton;
    private javax.swing.JButton filterButton;
    private java.awt.Button freqDown;
    private java.awt.Button freqUp;
    private javax.swing.JTextField inputVFO;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField mode;
    private javax.swing.JButton modeButton;
    public javax.swing.JTextField msID;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JTextField vfo;
    private javax.swing.JButton vfoAtoB;
    // End of variables declaration//GEN-END:variables

    private Client client;

    private JPopupMenu modeMenu;
    private JPopupMenu filterMenu;
    private JPopupMenu agcMenu;
    private JPopupMenu dspMenu;
    private JPopupMenu gainMenu;

    private JRadioButtonMenuItem lsb;
    private JRadioButtonMenuItem usb;
    private JRadioButtonMenuItem am;
    private JRadioButtonMenuItem sam;

    private long frequency;
    private String modeString="";
    
    private DecimalFormat mhzFormat=new DecimalFormat("####0");
    private DecimalFormat khzFormat=new DecimalFormat("000000");

}
